### ISSUE TITLE
SPT 2.0.1 !

### ISSUE THREAD

**Issue by ByYasin** [JoakimCarlsson/EscapeFromTarkov-CP#1]
SPT 2.0.1 Can you update for?

**Comment by ByYasin** [comment]
"IsYourPlayer" = Error
I tried to update it, but it does not accept the word in the encoding, it gives an error?

**Comment by ByYasin** [comment]
Which SPT dll files are required as reference files for k?

**Comment by JoakimCarlsson** [comment]
This is an very old source, if I get the time this week i'll download SPT and update it.

**Comment by ByYasin** [comment]
> Bu çok eski bir kaynak, bu hafta vakit bulursam SPT'yi indirip güncelleyeceğim.


Thank you, there are many people waiting, this situation will be good.

**Comment by ByYasin** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/28735823/135712833-05f38b49-a779-4271-ba93-495601fe16db.png)

They have updated it as in the picture, but it needs to be updated for the previous version 2.0.1 SPT.

**Comment by ByYasin** [comment]
> This is an very old source, if I get the time this week i'll download SPT and update it.

@JoakimCarlsson

**Comment by ByYasin** [comment]
> This is an very old source, if I get the time this week i'll download SPT and update it.
