### ISSUE TITLE
Hi Help?

### ISSUE THREAD

**Issue by ByYasin** [JoakimCarlsson/EscapeFromTarkov-CP#6]
Can it be updated to the latest version of SPT-AKI for project work?

**Comment by JoakimCarlsson** [comment]
@ByYasin I can take a look, but i I can't make any promises. 

I have not touched EFT in a while.

**Comment by ByYasin** [comment]
Please update for the latest version of spt-aki, we are looking forward to it.

**Comment by ByYasin** [comment]
@JoakimCarlsson 
Were you able to look?

**Comment by JoakimCarlsson** [comment]
@ByYasin 
No, not yet sadly.

**Comment by ByYasin** [comment]
@JoakimCarlsson 
Ok.

**Comment by ByYasin** [comment]
@JoakimCarlsson Hi, whats up.

**Comment by ByYasin** [comment]
@JoakimCarlsson 
Hello, have you had a chance to take a look?

**Comment by ByYasin** [comment]
![EscapeFromTarkov_LLxr80fMHO](https://github.com/JoakimCarlsson/EscapeFromTarkov-CP/assets/28735823/39869f00-c457-4580-8a3a-90eb5ae6482c)

Latest version 
It needs to be adapted and updated. Because the best offline cheat for spt aki is yours.

**Comment by infiSTAR** [comment]
@JoakimCarlsson what is your current discord?

**Comment by JoakimCarlsson** [comment]
> @JoakimCarlsson what is your current discord?

@infiSTAR the same as before JCarlsson#5643.

**Comment by antho0831** [comment]
Hello, I am new, can someone help me with the installation please?

**Comment by JoakimCarlsson** [comment]
> Hello, I am new, can someone help me with the installation please?

Hello.
Before this can be used it has to be updated.

**Comment by antho0831** [comment]
Hello
When will it be updated?

Thank

**Comment by JoakimCarlsson** [comment]
> Hello When will it be updated?
> 
> Thank

When someone creates a PR for it.
I do not have the time to update this.
